services:
  novnc:
    restart: unless-stopped
    build:
      context: im_novnc
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      - VNC_HOST=ip/or/host
      - VNC_PORT=5900
    networks:
      - novnc
networks:
  novnc:
